In [1]:
from sklearn import tree
import pandas as pd
import os

In [2]:
QB_data = pd.read_csv("../nfl-project3/QB Machine Learning.csv")

In [3]:
QB_data

,Height,Weight,Hand Size,Arm Length,Wonderlic,FortyYard,BenchPress,VertLeap,BroadJump,Shuttle,ThreeCone,Touches,Pct,Y_A,PassTDPct,IntPct,RushTDPct,RushAvg,RookieAV
0,70.625,204,10.25,31.00,28.0,4.53,NaN,34.0,118.0,4.09,6.97,1930,60.9,7.9,0.073,0.020,0.052,3.2,70
1,77.000,248,9.88,33.75,21.0,4.56,NaN,35.0,126.0,4.18,6.92,577,65.4,10.0,0.103,0.024,0.084,5.6,63
2,74.250,226,10.88,32.25,NaN,4.79,NaN,32.5,116.0,4.32,7.11,1705,62.8,8.0,0.060,0.020,0.076,4.7,60
3,76.750,228,9.50,32.63,32.0,4.94,NaN,NaN,NaN,4.51,7.40,1515,59.9,6.9,0.042,0.027,0.065,0.3,55
4,78.380,236,9.63,33.13,27.0,4.86,NaN,28.5,110.0,4.27,6.82,10,25.0,2.8,0.000,0.000,0.000,0.0,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,77.000,253,9.75,33.75,NaN,4.81,NaN,36.0,NaN,NaN,NaN,422,61.7,8.6,0.056,0.026,0.026,4.0,0
308,76.375,223,9.00,32.00,NaN,4.78,NaN,31.0,114.0,4.33,7.04,1443,56.1,6.8,0.039,0.025,0.029,-1.2,0
309,76.000,217,9.75,33.00,NaN,4.79,NaN,33.0,113.0,4.28,7.21,1346,57.5,7.9,0.061,0.019,0.017,1.2,0
310,75.000,207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1272,61.7,7.3,0.050,0.025,0.063,2.9,0
311,75.750,229,10.00,32.63,35.0,4.86,NaN,29.5,108.0,4.45,7.52,1822,55.5,7.3,0.052,0.027,0.022,-3.1,-4

In [4]:
target = QB_data["RookieAV"]

In [14]:
data = QB_data.drop("RookieAV", axis=1)
data.fillna(data.mean(), inplace=True)
feature_names = data.columns
data.head()

,Height,Weight,Hand Size,Arm Length,Wonderlic,FortyYard,BenchPress,VertLeap,BroadJump,Shuttle,ThreeCone,Touches,Pct,Y_A,PassTDPct,IntPct,RushTDPct,RushAvg
0,70.625,204,10.25,31.00,28.000000,4.53,19.421053,34.000000,118.000000,4.09,6.97,1930,60.9,7.9,0.073,0.020,0.052,3.2
1,77.000,248,9.88,33.75,21.000000,4.56,19.421053,35.000000,126.000000,4.18,6.92,577,65.4,10.0,0.103,0.024,0.084,5.6
2,74.250,226,10.88,32.25,27.168919,4.79,19.421053,32.500000,116.000000,4.32,7.11,1705,62.8,8.0,0.060,0.020,0.076,4.7
3,76.750,228,9.50,32.63,32.000000,4.94,19.421053,31.142857,110.112554,4.51,7.40,1515,59.9,6.9,0.042,0.027,0.065,0.3
4,78.380,236,9.63,33.13,27.000000,4.86,19.421053,28.500000,110.000000,4.27,6.82,10,25.0,2.8,0.000,0.000,0.000,0.0

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [7]:
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

-0.478976151696924

In [8]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=5000)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.1994366332674955

In [9]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.13319755666091096, 'Height'),
 (0.11192238754636227, 'FortyYard'),
 (0.10353385740261165, 'Wonderlic'),
 (0.07757105291430258, 'Hand Size'),
 (0.07146689474686811, 'Y_A'),
 (0.06723951121151747, 'RushAvg'),
 (0.06714900135230663, 'PassTDPct'),
 (0.05613123082368961, 'Pct'),
 (0.047075376565448655, 'RushTDPct'),
 (0.042377723219427774, 'Touches'),
 (0.03411783102896391, 'Weight'),
 (0.03198330016546049, 'Arm Length'),
 (0.029245080945299654, 'ThreeCone'),
 (0.028949718660266355, 'IntPct'),
 (0.0257255560361506, 'Shuttle'),
 (0.0256928815047024, 'BroadJump'),
 (0.0244779179105271, 'BenchPress'),
 (0.022143121305183956, 'VertLeap')]

In [15]:
row = [[74.125, 225, 9.25, 33.25, 24, 4.8, 19.421053, 30, 114, 4.08, 6.88, 1657, 63.5, 8.3, .069, .021, .071, 2.7]]
yhat = rf.fit(X_train, y_train).predict(row)
print('Prediction: %d' % yhat[0])

Prediction: 4